version: "3.7"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: traefik
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/traefik/traefik.yml:/traefik.yml:ro"
      - "/opt/traefik/acme.json:/acme.json"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=false"
    # @DEBUG
      # - "traefik.enable=true"
      # - "traefik.http.routers.http-catchall.entrypoints=web"
      # - "traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.*}`)"
      # - "traefik.http.routers.http-catchall.middlewares=https-redirect"
      # - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.routers.dashboard.entrypoints=websecure"
      # - "traefik.http.routers.dashboard.tls=true"
      # - "traefik.http.routers.dashboard.tls.certresolver=le"
      # - "traefik.http.routers.dashboard.rule=Host(`[instance-url]`) && Path(`/traefik-dashboard`)"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true